INSERT INTO AUTHOR VALUES('AA00001','Microcomputer Keyboarding and Document Processing');
INSERT INTO AUTHOR VALUES('AA00002','The Latext Companion');
INSERT INTO AUTHOR VALUES('AA00003','Pagemaker 4 for the PC');
INSERT INTO AUTHOR VALUES('AA00004','Macintosh Revealed vol.1');
INSERT INTO AUTHOR VALUES('AA00005','Inside the Norton Utilities 6.0(3rd ed.)');
INSERT INTO AUTHOR VALUES('AA00006','Wordperfect 5.1 Tips, Tricks and Traps(3rd ed)	');
INSERT INTO AUTHOR VALUES('AA00007','IBM Using Disk Operating System Version 4');
INSERT INTO AUTHOR VALUES('AA00008','Mastering Harvard Graphics');
INSERT INTO AUTHOR VALUES('AA00009','Fix Your Own PC');
INSERT INTO AUTHOR VALUES('AA00010','Fix Your Own PC');
INSERT INTO AUTHOR VALUES('AA00011','DOS The Complete Reference (4th ed.)');
INSERT INTO AUTHOR VALUES('AA00012','Microcomputers and Microprocessors');
INSERT INTO AUTHOR VALUES('AA00013','Microcomputer Systems: The 8086/8088 family');
INSERT INTO AUTHOR VALUES('AA00014','Pagemaker 4 by Example');
INSERT INTO AUTHOR VALUES('AA00015','Latex for Everyone');
INSERT INTO AUTHOR VALUES('AA00016','IBM PC Advanced  Troubleshooting');
INSERT INTO AUTHOR VALUES('AA00017','Lotus 123 (Practical Applications)');
INSERT INTO AUTHOR VALUES('AA00018','Microsoft MSDOS vers 4');
INSERT INTO AUTHOR VALUES('AA00019','Using Windows 3.0/3.1');
INSERT INTO AUTHOR VALUES('AA00020','Word for Windows ( quick reference)');